---
title: "Untitled"
author: "yuki"
date: "2025-12-05"
output: html_document
---
```{r}
binaryRL.res <- binaryRL::run_m(
  mode = "fit",
  data = binaryRL::Mason_2024_G2,
  id = 1,
  n_params = 3,
  n_trials = 360,
  pi = 0.1,
  eta = c(0.3, 0.7),
  tau = c(0.5), 
  priors = list(
    eta = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    tau = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
  ),
  policy = "off",
)

summary(binaryRL.res)

multiRL.model <- multiRL::run_m(
  data = binaryRL::Mason_2024_G2[binaryRL::Mason_2024_G2[, "Subject"] == 1, ],
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  params = list(
    free = list(
      alphaN = 0.3,
      alphaP = 0.7,
      beta = 0.5
    )
  ),
  priors = list(
    alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
  ),
  settings = list(
    name = "RSTD",
    mode = "fitting",
    estimate = "MLE",
    policy = "off"
  )
)

multiRL.summary <- multiRL::summary(multiRL.model)
```


```{r}
binaryRL_r <- function(x) {
  binaryRL.res <- binaryRL::run_m(
    mode = "fit",
    data = binaryRL::Mason_2024_G2,
    id = 1,
    n_params = 3,
    n_trials = 360,
    initial_value = 100,
    threshold = 1,
    pi = 0.1,
    epsilon = NA_real_,
    eta = c(0.3, 0.7),
    tau = c(0.5), 
    priors = list(
      eta = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      tau = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    ),
    policy = "on",
    engine = "r"
  )
}
```

```{r}
binaryRL_cpp <- function(x) {
  binaryRL.res <- binaryRL::run_m(
    mode = "fit",
    data = binaryRL::Mason_2024_G2,
    id = 1,
    n_params = 3,
    n_trials = 360,
    initial_value = 100,
    threshold = 1,
    pi = 0.1,
    epsilon = NA_real_,
    eta = c(0.3, 0.7),
    tau = c(0.5), 
    priors = list(
      eta = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      tau = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    ),
    policy = "on",
    engine = "cpp"
  )
}
```

```{r}
multiRL_r <- function(x) {
  multiRL.model <- multiRL::run_m(
    data = binaryRL::Mason_2024_G2[binaryRL::Mason_2024_G2[, "Subject"] == 1, ],
    behrule = list(
      cue = c("A", "B", "C", "D"),
      rsp = c("A", "B", "C", "D")
    ),
    colnames = list(
      subid = "Subject", block = "Block", trial = "Trial",
      object = c("L_choice", "R_choice"), 
      reward = c("L_reward", "R_reward"),
      action = "Sub_Choose",
      exinfo = c("Frame", "NetWorth", "RT")
    ),
    params = list(
      free = list(
        alphaN = 0.3,
        alphaP = 0.7,
        beta = 0.5
      ),
      constant = list(
        Q0 = 100, 
        lapse = 0.01,
        bonus = 0
      )
    ),
    priors = list(
      alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    ),
    settings = list(
      name = "RSTD",
      mode = "fitting",
      estimate = "MLE",
      policy = "on",
      system = c("RL", "WM")
    ),
    engine = "R",
    anythingelse = c(1, 2, 3)
  )
}
```

```{r}
multiRL_cpp <- function(x) {
  multiRL.model <- multiRL::run_m(
    data = binaryRL::Mason_2024_G2[binaryRL::Mason_2024_G2[, "Subject"] == 1, ],
    behrule = list(
      cue = c("A", "B", "C", "D"),
      rsp = c("A", "B", "C", "D")
    ),
    colnames = list(
      subid = "Subject", block = "Block", trial = "Trial",
      object = c("L_choice", "R_choice"), 
      reward = c("L_reward", "R_reward"),
      action = "Sub_Choose",
      exinfo = c("Frame", "NetWorth", "RT")
    ),
    params = list(
      free = list(
        alphaN = 0.3,
        alphaP = 0.7,
        beta = 0.5
      ),
      constant = list(
        Q0 = 100, 
        lapse = 0.01,
        bonus = 0
      )
    ),
    priors = list(
      alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    ),
    settings = list(
      name = "RSTD",
      mode = "fitting",
      estimate = "MLE",
      policy = "on",
      system = c("RL", "WM")
    ),
    engine = "Cpp",
    anythingelse = c(1, 2, 3)
  )
}
```

```{r}
profvis::profvis({
  for (i in 1:50) {
    multiRL_cpp()
  }
})
```


```{r}
mb <- microbenchmark::microbenchmark(
  binaryRL_r = binaryRL_r(),
  binaryRL_cpp = binaryRL_cpp(),
  multiRL_r = multiRL_r(),
  multiRL_cpp = multiRL_cpp(),
  times = 100
)
```

```{r}
as.data.frame(mb) |>
  dplyr::group_by(expr) |>
  dplyr::mutate(
    run_id = dplyr::row_number(),
    time = time / 1e6
  ) |>
  dplyr::ungroup() |>
  tidyr::pivot_wider(
    names_from  = expr,
    values_from = time
  ) |>
  tidyr::pivot_longer(
    cols = -run_id,
    names_to  = "method",
    values_to = "time_ms"
  ) |>
  ggplot2::ggplot(
    ggplot2::aes(x = method, y = time_ms, fill = method, color = method)
  ) +
  ggplot2::geom_violin(
    trim = FALSE,
    alpha = 0.6
  ) +
  ggplot2::geom_boxplot(
    width = 0.12,
    outlier.shape = NA,
    alpha = 0.6
  ) +
  ggplot2::scale_y_continuous(
    limits = c(0, 220),
    breaks = seq(0, 220, by = 10)
  ) +
  ggplot2::scale_fill_manual(
    values = c(
      "binaryRL_cpp" = "#ff6b6b",  # 紫色（C++）
      "multiRL_cpp"  = "#ffd93d",  # 浅紫（C++）
      "binaryRL_r"   = "#6bcb77",  # 蓝色（R）
      "multiRL_r"    = "#4d96ff"   # 浅蓝（R）
    )
  ) +
  ggplot2::scale_color_manual(
    values = c(
      "binaryRL_cpp" = "#ff6b6b",  # 紫色（C++）
      "multiRL_cpp"  = "#ffd93d",  # 浅紫（C++）
      "binaryRL_r"   = "#6bcb77",  # 蓝色（R）
      "multiRL_r"    = "#4d96ff"   # 浅蓝（R）
    )
  ) +
  ggplot2::labs(
    x = NULL,
    y = "Runtime (ms)",
    fill = "Package_Language"
  ) +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = "none")


ggplot2::ggsave(filename = "./benchmark.png", width = 6, height = 8)
```

