---
title: "Untitled"
author: "yuki"
date: "2025-10-15"
output: html_document
---
# multiRL

```{r}
multiRL.input <- multiRL::process_1_input(
  data = multiRL::MAB[multiRL::MAB[, "Subject"] == 1, ],
  colnames = list(
    subid = "Subject", block = "Block", trial = "Trial",
    object = NA_character_, reward = NA_character_, action = "Action"
  ),
  params = list(
    free = list(
      alphaN = 0.3,
      alphaP = 0.7,
      beta = 0.5
    )
  ),
  priors = list(
    alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
  ),
  settings = list(
    name = "RSTD",
    mode = "fitting",
    estimate = "MLE",
    policy = "on"
  )
)
```

```{r}
multiRL.behrule <- multiRL::process_2_behrule(
  behrule = list(
    cue = c("Red", "Yellow", "Green", "Blue"),
    rsp = c("Up", "Down", "Left", "Right")
  )
)
```

```{r}
multiRL.record <- multiRL::process_3_record(
  input = multiRL.input,
  behrule = multiRL.behrule
)
```

```{r}
multiRL.output <- multiRL::process_4_output_r(
  record = multiRL.record,
  extra = multiRL.record@extra
)

multiRL.output <- multiRL::process_4_output_cpp(
  record = multiRL.record,
  extra = multiRL.record@extra
)
```

```{r}
multiRL.metric <- process_5_metric(
  output = multiRL.output
)
```

```{r}
View(multiRL.output@result@value)
View(multiRL.output@result@reward)
View(multiRL.output@result@utility)
View(multiRL.output@result@count)
View(multiRL.output@result@bias)
View(multiRL.output@result@shown)
View(multiRL.output@result@exploration)
View(multiRL.output@result@prob)
```

```{r}
multiRL.model <- multiRL::run_m(
  engine = "Cpp",
  data = multiRL::MAB[multiRL::MAB[, "Subject"] == 1, ],
  behrule = list(
    cue = c("Red", "Yellow", "Green", "Blue"),
    rsp = c("Up", "Down", "Left", "Right")
  ),
  params = list(
    free = list(
      alphaN = 0.3,
      alphaP = 0.7,
      beta = 0.5,
      delta = 0,
      sticky = 100
    )
  ),
  settings = list(
    name = "unknown",
    mode = "fitting",
    estimate = "MLE",
    policy = "on",
    system = c("RL", "WM")
  ),
  anythingelse = c(1, 2, 3)
)

multiRL.summary <- multiRL::summary(multiRL.model)
```

## binaryRL

```{r}
multiRL.model <- multiRL::run_m(
  engine = "Cpp",
  #engine = "R",
  data = binaryRL::Mason_2024_G2[binaryRL::Mason_2024_G2[, "Subject"] == 1, ],
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  colnames = list(
    subid = "Subject", block = "Block", trial = "Trial",
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose",
    exinfo = c("Frame", "NetWorth", "RT")
  ),
  params = list(
    free = list(
      alpha = 0.5,
      beta = 0.01,
      delta = 0,
      sticky = 100,
      reset = 999
    ),
    constant = list(
      Q0 = 100,
      weight = 1
    )
  ),
  priors = list(
    alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
  ),
  settings = list(
    name = "RSTD",
    mode = "fitting",
    estimate = "MLE",
    policy = "on",
    system = c("RL", "WM")
    #system = "RL"
  ),
  anythingelse = c(1, 2, 3)
)

multiRL.summary <- multiRL::summary(multiRL.model)
```

Model Fit:
  Accuracy: 100%
  Log-Likelihood: -394.07
  Log-Prior Probability: -0.04
  Log-Posterior Probability: -394.11
  AIC: 794.14
  BIC: 805.8

```{r}
binaryRL.res <- binaryRL::run_m(
  mode = "fit",
  data = binaryRL::Mason_2024_G2,
  id = 1,
  n_params = 3,
  n_trials = 360,
  initial_value = 100,
  threshold = 1,
  pi = 0.1,
  epsilon = NA_real_,
  eta = c(0.3, 0.7),
  tau = c(0.5), 
  priors = list(
    eta = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    tau = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
  ),
  policy = "off"
)

summary(binaryRL.res)
```

```{r}
multiRL.input <- multiRL::process_1_input(
  data = multiRL::TAB[multiRL::TAB[, "Subject"] == 1, ],
  colnames = list(
    subid = "Subject", 
    block = "Block",
    trial = "Trial",
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose",
    exinfo = c("Frame", "NetWorth", "RT")
    #extra = NA_character_
  ),
  params = list(
    free = list(
      alpha = 0.5,
      beta = 0.01,
      delta = 0
    ),
    constant = list(
      weight = c(1, 0)
    )
  ),
  priors = list(
    alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)},
    alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)},
    beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
  ),
  settings = list(
    name = "RSTD",
    mode = "fitting",
    estimate = "MLE",
    policy = "off",
    #system = c("RL", "WM")
    system = "RL"
  )
)
```

```{r}
multiRL.behrule <- multiRL::process_2_behrule(
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  )
)
```

```{r}
multiRL.record <- multiRL::process_3_record(
  input = multiRL.input,
  behrule = multiRL.behrule
)
```

```{r}
multiRL.output <- multiRL::process_4_output_r(
  record = multiRL.record,
  extra = multiRL.record@extra
)
```

```{r}
multiRL.metric <- process_5_metric(
  output = multiRL.output
)
```

```{r}
View(multiRL.output@result@value$RL)
View(multiRL.output@result@value$WM)

View(multiRL.output@input@features@action)
View(multiRL.output@result@reward)
View(multiRL.output@result@utility)
View(multiRL.output@result@count)
View(multiRL.output@result@bias)
View(multiRL.output@result@shown)
View(multiRL.output@result@prob)
View(multiRL.output@result@simulation)
View(multiRL.output@result@latent)
```


