---
title: "Untitled"
author: "yuki"
date: "2025-11-06"
output: html_document
---

## ABC
```{r}
data = multiRL::TAB[multiRL::TAB[, "Subject"] == 1, ]

behrule = list(
  cue = c("A", "B", "C", "D"),
  rsp = c("A", "B", "C", "D")
)
# 列名, 数据集中的列名
colnames = list(
  object = c("L_choice", "R_choice"), 
  reward = c("L_reward", "R_reward"),
  action = "Sub_Choose"
)
# 额外设定, 关键在于mode, 如果是ABC, 则一定使用的是模拟数据, 所以是simulating
settings = list(
  name = "RSTD",
  mode = "simulating",
  estimate = "ABC",
  policy = "on"
)
# 生成的随机数, 取自哪个分布
priors = list(
  alphaN = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
  alphaP = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
  beta = function(x) {stats::rexp(n = 1, rate = 1)}
)
# 使用的哪个强化学习模型
model = multiRL::RSTD
# 生成多少个模拟数据集, 使用多少个核心用于生成
# 核心数量, 在任务管理器里查看, 尽可能多
control = list(sample = 100, core = 1)
```

```{r}
multiRL.env <- multiRL::estimate_0_ENV(
  data = data,
  behrule = behrule,
  colnames = colnames,
  settings = settings,
)
```

```{r}
list_simulated <- multiRL::estimate_2_SBI(
  model = model,
  env = multiRL.env,
  priors = priors,
  control = control
)
```

```{r}
list_train <- list_simulated[1:1000]
list_valid <- list_simulated[1001:1100]


#Step 1: Free Parameters
extract_params <- function(x) {
  param_vector <- unlist(x$params)      
  names(param_vector) <- names(x$params)  
  return(param_vector)
}


# parameters for training
df_train.params <- dplyr::bind_rows(
  .x = purrr::map(.x = list_train, .f = extract_params)
)

df_valid.params <- dplyr::bind_rows(
  .x = purrr::map(.x = list_valid, .f = extract_params)
)

#Step 2: Summary Statistics
extract_sumstats <- function(x) {
  stats_vector <- x$sumstat
  names(stats_vector) <- colnames(x$sumstat)
  return(stats_vector)
}

df_train.sumstats <- dplyr::bind_rows(
  .x = purrr::map(.x = list_train, .f = extract_sumstats)
)

df_valid.sumstats <- dplyr::bind_rows(
  .x = purrr::map(.x = list_valid, .f = extract_sumstats)
)


```

```{r}
#Step 3: Training ABC Model
df_true <- df_valid.params
df_pred <- data.frame(
  alphaN = NA,
  alphaP = NA,
  beta = NA
)

for (i in 1:100) {
  result <- abc::abc(
    target = as.vector(df_valid.sumstats[i, ]), 
    param = df_train.params, 
    sumstat = df_train.sumstats, 
    tol = .1, 
    method = "neuralnet", 
    transf = c("logit", "logit","logit"),
    logit.bounds = rbind(c(0, 1), c(0, 1), c(0, 5))
  )
  
  df_pred[i, ] <- summary(result)[5, ]
}

```

```{r}
#Parameter Recovery
cor(df_true$alphaN, df_pred$alphaN)
cor(df_true$alphaP, df_pred$alphaP)
cor(df_true$beta, df_pred$beta)

```

```{r}
result.ABC <- multiRL::estimate_2_ABC(
  data = multiRL::TAB,
  ids = 1:10,
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD, multiRL::RSTD, multiRL::Utility),
  
  priors = list(
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    ),
    list(
      alphaN = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      alphaP = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    ),
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)},
      gamma = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}
    )
  ),
  settings = list(list(name = "TD"), list(name = "RSTD"), list(name = "Utility")),
  
  lowers = list(c(0, 0), c(0, 0, 0), c(0, 0, 0)),
  uppers = list(c(1, 5), c(1, 1, 5), c(1, 1, 5)),
  control = list(
    scope = "individual",
    #scope = "shared",
    core = 10,
    tol = 0.1,
    sample = 100,
    train = 100
  )
)
```

```{r}
recovery.ABC <- multiRL::rcv_d(
  estimate = "ABC",

  data = data,
  behrule = behrule,
  colnames = colnames,

  models = list(multiRL::TD),
  priors = list(
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    )
  ),
  settings = list(name = c("TD")),
  
  lowers = list(c(0, 0)),
  uppers = list(c(1, 10)),
  control = list(
    core = 10, sample = 100, train = 1000,
    tol = 0.2, reduction = "PCA"
    #loss = "NLL", check = FALSE
  )
)
```

## RNN

```{r}
data <- multiRL::TAB
behrule = list(
  cue = c("A", "B", "C", "D"),
  rsp = c("A", "B", "C", "D")
)
colnames = list(
  subid = "Subject", block = "Block", trial = "Trial",
  object = c("L_choice", "R_choice"), 
  reward = c("L_reward", "R_reward"),
  action = "Sub_Choose",
  exinfo = c("Frame", "NetWorth", "RT")
)
```

```{r}
reticulate::use_condaenv(condaenv = "tf-gpu", required = TRUE)
```

```{r}
recovery.RNN <- multiRL::rcv_d(
  estimate = "RNN",

  data = data,
  behrule = behrule,
  colnames = colnames,

  models = list(multiRL::TD),
  priors = list(
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    )
  ),
  settings = list(name = c("TD")),
  
  lowers = list(c(0, 0)),
  uppers = list(c(1, 10)),
  control = list(
    core = 10, sample = 100, train = 1000,
    #tol = 0.5, reduction = "PCA", 
    layer = "GRU", loss = "MSE", check = FALSE, dropout = 0, L = 2
  )
)
```

