---
title: "Raw Data"
author: "yuki"
date: "2025-09-19"
output: html_document
---
```{r}
# --- 1. 定义实验参数 (与之前相同) ---
n_subjects <- 30
n_blocks <- 6
n_trials_per_block <- 50
object_colors <- c("Red", "Yellow", "Green", "Blue")
directions <- c("Up", "Down", "Left", "Right")
df_base <- tidyr::expand_grid(
  Subject = 1:n_subjects,
  Block = 1:n_blocks,
  Trial = 1:n_trials_per_block
)
n_rows <- nrow(df_base)


# --- 2. 为每个 Object 列独立创建并洗牌平衡池 ---

# 计算每种方向在单个列中应出现的次数 (9000行 / 4个方向)
reps_per_direction <- n_rows / length(directions) # 9000 / 4 = 2250

# 创建一个辅助函数, 用于为单一颜色生成一个平衡且打乱的列
create_shuffled_column <- function(color, dirs, reps) {
  # 1. 创建该颜色的所有方向组合 (如 "Red_Up", "Red_Down"...)
  combinations <- paste(color, dirs, sep = "_")
  # 2. 创建一个包含 9000 个刺激的完美平衡池
  pool <- rep(combinations, times = reps)
  # 3. 独立打乱这个池并返回结果
  shuffled_col <- sample(pool)
  return(shuffled_col)
}

# 为了可复现性, 设置种子
set.seed(42)

# 为四个 Object 列分别独立地生成平衡且打乱的内容
col_obj1_red <- create_shuffled_column(
  object_colors[1], directions, reps_per_direction
)
col_obj2_yellow <- create_shuffled_column(
  object_colors[2], directions, reps_per_direction
)
col_obj3_green <- create_shuffled_column(
  object_colors[3], directions, reps_per_direction
)
col_obj4_blue <- create_shuffled_column(
  object_colors[4], directions, reps_per_direction
)


# --- 3. 将生成的列合并到最终的数据框 ---

# 将基础信息和四个独立生成的 Object 列合并
df_object <- df_base %>%
  dplyr::mutate(
    Object_1 = col_obj1_red,
    Object_2 = col_obj2_yellow,
    Object_3 = col_obj3_green,
    Object_4 = col_obj4_blue
  )


# --- 4. 检查和验证结果 ---

# 验证全局数量是否依然平衡
summary_balanced <- df_object %>%
  tidyr::pivot_longer(
    cols = starts_with("Object_"),
    values_to = "Combination"
  ) %>%
  dplyr::count(Combination, sort = TRUE, name = "Total_Count")

print(summary_balanced)


# --- 5. 清理中间变量 ---
rm(
  n_subjects, n_blocks, n_trials_per_block,
  object_colors, directions, n_rows, reps_per_direction,
  create_shuffled_column,
  col_obj1_red, col_obj2_yellow, col_obj3_green, col_obj4_blue,
  summary_balanced
)
```

```{r}
# --- 1. 定义一个函数, 用于生成单个 block (50次) 的奖励 ---

# 这个函数会返回一个 50行 x 4列 的数据框, 包含四种奖励
generate_reward_block <- function(n_trials = 50) {

  # --- Deck A / Reward_1: 高收益, 高频中额罚款 ---
  # 50次试验中, 总罚款需要是 50*100 - (-1250) = 6250
  # 罚款次数为 (50/10)*5 = 25次, 每次罚款 6250/25 = 250
  punishments_A <- sample(c(rep(-250, 25), rep(0, 25)))
  reward_A <- 100 + punishments_A

  # --- Deck B / Reward_2: 高收益, 低频巨额罚款 ---
  # 总罚款同样是 6250
  # 罚款次数为 (50/10)*1 = 5次, 每次罚款 6250/5 = 1250
  punishments_B <- sample(c(rep(-1250, 5), rep(0, 45)))
  reward_B <- 100 + punishments_B

  # --- Deck C / Reward_3: 低收益, 高频小额罚款 ---
  # 50次试验中, 总罚款需要是 50*50 - 1250 = 1250
  # 罚款次数为 (50/10)*5 = 25次, 每次罚款 1250/25 = 50
  punishments_C <- sample(c(rep(-50, 25), rep(0, 25)))
  reward_C <- 50 + punishments_C

  # --- Deck D / Reward_4: 低收益, 低频中额罚款 ---
  # 总罚款同样是 1250
  # 罚款次数为 (50/10)*1 = 5次, 每次罚款 1250/5 = 250
  punishments_D <- sample(c(rep(-250, 5), rep(0, 45)))
  reward_D <- 50 + punishments_D

  # 将四列奖励合并成一个 tibble 并返回
  return(
    tibble::tibble(
      Reward_1 = reward_A,
      Reward_2 = reward_B,
      Reward_3 = reward_C,
      Reward_4 = reward_D
    )
  )
}

# --- 2. 为所有 block 生成奖励并合并 ---

# 计算数据集中总共有多少个独立的 block
n_total_blocks <- df_object %>%
  dplyr::distinct(Subject, Block) %>%
  nrow() # 结果是 180

df_reward <- purrr::map_dfr(
  .x = 1:n_total_blocks,
  .f = ~ generate_reward_block()
) %>%
  dplyr::bind_cols(df_object, .)

# --- 3. 验证结果 ---

# 验证每个 block 内的奖励总和是否精确符合要求
verification_rewards <- df_reward %>%
  dplyr::group_by(Subject, Block) %>%
  dplyr::summarise(
    Sum_Reward_1 = sum(Reward_1),
    Sum_Reward_2 = sum(Reward_2),
    Sum_Reward_3 = sum(Reward_3),
    Sum_Reward_4 = sum(Reward_4),
    .groups = "drop"
  )

verification_rewards

rm(generate_reward_block, verification_rewards, n_total_blocks)
```

```{r}
data <- df_reward %>%
  dplyr::mutate(Sub_Choose = NA_character_)

rm(df_base, df_object, df_reward)
```

