---
title: "Untitled"
author: "yuki"
date: "2025-11-06"
output: html_document
---
```{r}

data = multiRL::TAB[multiRL::TAB[, "Subject"] == 1, ]

behrule = list(
  cue = c("A", "B", "C", "D"),
  rsp = c("A", "B", "C", "D")
)

colnames = list(
  object = c("L_choice", "R_choice"), 
  reward = c("L_reward", "R_reward"),
  action = "Sub_Choose"
)

settings = list(
  name = "RSTD",
  mode = "simulating",
  estimate = "RNN",
  policy = "on"
)

priors = list(
  alphaN = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
  alphaP = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
  beta = function(x) {stats::rexp(n = 1, rate = 1)}
)

model = multiRL::RSTD

control = list(sample = 1100, core = 16)
```

```{r}
multiRL.env <- estimate_0_ENV(
  data = data,
  behrule = behrule,
  colnames = colnames,
  settings = settings,
)
```

```{r}
list_simulated <- estimate_2_SBI(
  model = model,
  env = multiRL.env,
  priors = priors,
  control = control
)
```

```{r}
n_sample <- 1000
n_trials <- nrow(list_simulated[[1]]$matrix)
n_info <- 3
n_params <- length(list_simulated[[1]]$params)

# Input: n_sample, n_trials, n_info
X <- array(NA, dim = c(n_sample, n_trials, n_info))

for (i in 1:n_sample) {
  X[i, , ] <- list_simulated[[i]]$matrix[, c("L_choice", "R_choice", "Sub_Choose"), drop = FALSE]
}

# Output: n_sample, n_params
Y <- array(NA, dim = c(n_sample, n_params))

for (i in 1:n_sample) {
  Y[i, ] <- unlist(list_simulated[[i]]$params)
}
```

```{r}
train_indices <- 1:floor(0.8 * n_sample)
valid_indices <- -train_indices

X_train <- X[train_indices, , , drop = FALSE]
X_valid <- X[valid_indices, , , drop = FALSE]

Y_train <- Y[train_indices, , drop = FALSE]
Y_valid <- Y[valid_indices, , drop = FALSE]
```

```{r}
#reticulate::use_condaenv("tf-cpu", required = TRUE)
reticulate::use_condaenv("tf-gpu", required = TRUE)
```

```{r}
set.seed(123)

# Initialize Model (sequential decision making)
Model <- keras::keras_model_sequential()

algorithm = "GRU"
#algorithm = "LSTM"

# Recurrent Layer
switch(
  EXPR = algorithm, 
  "GRU" = {
    Model <- keras::layer_gru(
      object = Model,
      units = 128,
      input_shape = c(n_trials, n_info), 
      return_sequences = FALSE, 
    ) 
  },
  "LSTM" = {
    Model <- keras::layer_lstm(
      object = Model,
      units = 128,
      input_shape = c(n_trials, n_info), 
      return_sequences = FALSE, 
    ) 
  },
) |>
  # Hidden Layer
  keras::layer_dense(
    units = 64, 
    activation = "relu"
  ) |>
  # Output Layer
  keras::layer_dense(
    units = n_params, 
    activation = "linear"
  ) |>
  # Loss Function
  keras::compile(
    loss = "mean_squared_error",
    optimizer = "adam",
    metrics = c("mean_absolute_error")
  )

# Training RNN Model
history <- Model |>
  keras::fit(
    x = X_train,
    y = Y_train,
    epochs = 10,
    batch_size = 10,
    validation_data = list(X_valid, Y_valid),
    verbose = 2
  )
```

```{r}
X_pred_list <- vector("list", length = 10) 
X_true_list <- vector("list", length = 10)

for (i in (n_sample + 1):(n_sample + 10)) {

  X_sub <- array(NA, dim = c(1, n_trials, n_info))
  
  X_sub[1, , ] <- list_simulated[[i]]$matrix[, c("L_choice", "R_choice", "Sub_Choose"), drop = FALSE]

################################## [core] ######################################
  X_pred <- predict(object = Model, x = X_sub)
################################## [core] ######################################
  
  X_pred_list[[i - n_sample]] <- X_pred
  X_true_list[[i - n_sample]] <- unlist(list_simulated[[i]]$params)
}
```

```{r}
df_true <- as.data.frame(do.call(rbind, X_true_list))
df_pred <- as.data.frame(do.call(rbind, X_pred_list))

cor(df_true[[1]], df_pred[[1]])
cor(df_true[[2]], df_pred[[2]])
cor(df_true[[3]], df_pred[[3]])
```

## test

```{r}
reticulate::use_condaenv(condaenv = "tf-gpu", required = TRUE)
  
test <- multiRL::engine_RNN(
  data = multiRL::TAB[multiRL::TAB[, "Subject"] == 1, ],

  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  
  settings = list(
    name = "RSTD",
    mode = "simulating",
    estimate = "RNN",
    policy = "on"
  ),
  
  priors = list(
    alphaN = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
    alphaP = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
    beta = function(x) {stats::rexp(n = 1, rate = 1)}
  ),
  
  model = multiRL::RSTD,
  
  control = list(
    core = 16,
    
    layer = "GRU",
    units = 128,
    sample = 100,
    batch_size = 10,
    epochs = 20
  )
)
```

```{r}
multiRL.env <- estimate_0_ENV(
  data = multiRL::TAB[multiRL::TAB[, "Subject"] == 1, ],
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  settings = list(
    name = "RSTD",
    mode = "simulating",
    estimate = "RNN",
    policy = "on"
  ),
)
```

```{r}
list_simulated <- estimate_2_SBI(
  model = multiRL::RSTD,
  env = multiRL.env,
  priors = list(
    alphaN = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
    alphaP = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
    beta = function(x) {stats::rexp(n = 1, rate = 1)}
  ),
  control = list(sample = 200, core = 1)
)
```

```{r}
X_pred_list <- vector("list", length = 100) 
X_true_list <- vector("list", length = 100)

for (i in 101:200) {

  X_sub <- array(NA, dim = c(1, 360, 3))
  
  X_sub[1, , ] <- list_simulated[[i - 100]]$matrix[, c("L_choice", "R_choice", "Sub_Choose"), drop = FALSE]

################################## [core] ######################################
  X_pred <- stats::predict(object = test, x = X_sub)
################################## [core] ######################################
  
  X_pred_list[[i - 100]] <- X_pred
  X_true_list[[i - 100]] <- unlist(list_simulated[[i]]$params)
}
```

```{r}
df_true <- as.data.frame(do.call(rbind, X_true_list))
df_pred <- as.data.frame(do.call(rbind, X_pred_list))

cor(df_true[[1]], df_pred[[1]])
cor(df_true[[2]], df_pred[[2]])
cor(df_true[[3]], df_pred[[3]])
```

## n subject
```{r}
behrule = list(
  cue = c("A", "B", "C", "D"),
  rsp = c("A", "B", "C", "D")
)
colnames = list(
  object = c("L_choice", "R_choice"), 
  reward = c("L_reward", "R_reward"),
  action = "Sub_Choose"
)
settings = list(
  name = "RSTD",
  mode = "simulating",
  estimate = "RNN",
  policy = "on"
)
priors = list(
  alphaN = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
  alphaP = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
  beta = function(x) {stats::rexp(n = 1, rate = 1)}
)
model = multiRL::RSTD
control = list(
  core = 16,
  
  layer = "GRU",
  units = 128,
  sample = 100,
  batch_size = 10,
  epochs = 20
)
```


```{r}
info <- c(colnames$object, colnames$action)
opt_params <- list()
n_trials <- nrow(data)
n_info   <- length(info)
n_params <- length(priors)


for (i in 1:10) {
  data = multiRL::TAB[multiRL::TAB[, "Subject"] == i, ]
  
  RNN <- multiRL::engine_RNN(
    data = data,
    behrule = behrule,
    colnames = colnames,
    settings = settings,
    priors = priors,
    model = model,
    control = control
  )
  
  X_sub <- array(NA, dim = c(1, n_trials, n_info))
  X_sub[1, , ] <- .df2matrix(df = data)[, info, drop = FALSE]
  X_pred <- stats::predict(object = RNN, x = X_sub)
  names(X_pred) <- names(priors)
  
  opt_params[[i]] <- X_pred
}
```

```{r}
result <- do.call(rbind, opt_params)
colnames(result) <- names(priors)
```

```{r}
reticulate::use_condaenv(condaenv = "tf-gpu", required = TRUE)
```

```{r}
test <- estimate_2_RNN(
  data = multiRL::TAB %>% dplyr::filter(Subject %in% 1:3),
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD, multiRL::RSTD, multiRL::Utility),
  
  priors = list(
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    ),
    list(
      alphaN = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      alphaP = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    ),
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)},
      gamma = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}
    )
  ),
  settings = list(list(name = "TD"), list(name = "RSTD"), list(name = "Utility")),
  
  control = list(
    layer = "GRU",
    units = 128,
    sample = 100,
    batch_size = 10,
    epochs = 10
  )
)
```

```{r}
test1 <- list()

for (i in 1:length(test)) {
  test1[[i]] <- as.data.frame(test[[i]])
  colnames(test1[[i]]) <- names(priors[[i]])
}

test1 <- dplyr::bind_rows(test1)
```

