---
title: "Untitled"
author: "yuki"
date: "2025-11-21"
output: html_document
---
## MLE

```{r}
test_MLE <- estimation_methods(
  estimate = "MLE",
  data = multiRL::TAB %>% dplyr::filter(Subject %in% 1:10),
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD, multiRL::RSTD, multiRL::Utility),
  settings = list(list(name = "TD"), list(name = "RSTD"), list(name = "Utility")),
  
  algorithm = c("NLOPT_GN_MLSL", "NLOPT_LN_BOBYQA"),
  lowers = list(c(0, 0), c(0, 0, 0), c(0, 0, 0)),
  uppers = list(c(1, 1), c(1, 1, 1), c(1, 1, 1)),
  control = list(core = 10, iter = 10)
)
```


## MAP

```{r}
test_MAP <- estimation_methods(
  estimate = "MAP",
  data = multiRL::TAB %>% dplyr::filter(Subject %in% 1:10),
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD, multiRL::RSTD, multiRL::Utility),
  priors = list(
    TD = list(
      alpha = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    ),
    RSTD = list(
      alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    ),
    Utility = list(
      alpha = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)},
      gamma = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}
    )
  ),
  settings = list(list(name = "TD"), list(name = "RSTD"), list(name = "Utility")),
  
  algorithm = c("NLOPT_GN_MLSL", "NLOPT_LN_BOBYQA"),
  lowers = list(c(0, 0), c(0, 0, 0), c(0, 0, 0)),
  uppers = list(c(1, 5), c(1, 1, 5), c(1, 5, 1)),
  control = list(core = 10, iter = c(10, 6))
)
```

## RNN

```{r}
reticulate::use_condaenv(condaenv = "tf-gpu", required = TRUE)
```

```{r}
test_RNN <- estimation_methods(
  estimate = "RNN",
  data = multiRL::TAB %>% dplyr::filter(Subject %in% 1:3),
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD, multiRL::RSTD, multiRL::Utility),
  
  priors = list(
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    ),
    list(
      alphaN = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      alphaP = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    ),
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)},
      gamma = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}
    )
  ),
  settings = list(list(name = "TD"), list(name = "RSTD"), list(name = "Utility")),
  
  control = list(
    layer = "GRU",
    units = 128,
    sample = 100,
    batch_size = 10,
    epochs = 10
  )
)
```