---
title: "Untitled"
author: "yuki"
date: "2025-12-01"
output: html_document
---
```{r}
replay.recovery <- multiRL::rpl_e(
  result = recovery.MLE,
  #result = fitting.MLE,
  data = multiRL::TAB,
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD),
  settings = list(list(name = "TD", policy = "off")),
  omit = c("data", "funcs")
)

plot(replay.recovery)
```


```{r}
replay.recovery <- multiRL::rpl_e(
  result = recovery.MLE,
  #result = fitting.MLE,
  data = multiRL::TAB,
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD, multiRL::RSTD, multiRL::Utility),
  settings = list(list(name = "TD"), list(name = "RSTD"), list(name = "Utility")),
  omit = c("data", "funcs")
)
```

```{r}
names(replay.fitting)
names(replay.recovery)
```

```{r}

if (identical(c("simulate", "recovery"), names(replay))) {
  mode = "recovery"
} else {
  mode = "fitting"
}

.get_replay_params <- function(replay) {
  
  model_names <- names(replay)
  sub_names <- names(replay[[1]]) %||% 1:length(replay[[1]])
  
  free_params <- list()
  
  for (i in model_names) {
    for (j in sub_names) {
      free_params[[i]][[j]] <- unlist(
        replay[[i]][[j]]$multiRL.model@input@params@free
      )
      free_params[[i]][[j]] <- c(Subject = j, free_params[[i]][[j]])
    }
    free_params[[i]] <- as.data.frame(do.call(rbind, free_params[[i]]))
  }
  
  return(free_params)
}

test <- .get_replay_params(replay = replay.fitting)
test <- .get_replay_params(replay = replay.recovery$simulate)
test <- .get_replay_params(replay = replay.recovery$recovery$TD)


```

```{r}
free_params_names <- list()

for (i in model_names) {
  free_params_names[[i]] <- names(
    replay.recovery$simulate[[i]][[1]]$multiRL.summary@params@free
  )
}

true_alpha <- as.numeric(
  .get_replay_params(replay = replay.recovery$simulate)$TD$alpha
)
pred_alpha <- as.numeric(
  .get_replay_params(replay = replay.recovery$recovery$TD)$TD$alpha
)
cor(true_alpha, pred_alpha)
plot(true_alpha, pred_alpha)
```

```{r}
for (i in model_names) {
  
  for (j in free_params_names[[i]]) {
    
    ture <- as.numeric(
      .get_replay_params(replay = replay.recovery$simulate)[[i]][[j]]
    )
    pred <- as.numeric(
      .get_replay_params(replay = replay.recovery$recovery[[i]])[[i]][[j]]
    )
    print(paste0(i, ": ", j, ", r = ", round(cor(ture, pred), 2)))
    plot(
      x    = ture,
      y    = pred,
      main = paste0(i, ": ", j),
      xlab = "Simulated",
      ylab = "Fit"
    )
  }
}
```


