---
title: "Untitled"
author: "yuki"
date: "2025-11-27"
output: html_document
---
```{r}
data = multiRL::TAB[multiRL::TAB[, "Subject"] == 1, ]
behrule = list(
  cue = c("A", "B", "C", "D"),
  rsp = c("A", "B", "C", "D")
)
colnames = list(
  object = c("L_choice", "R_choice"), 
  reward = c("L_reward", "R_reward"),
  action = "Sub_Choose"
)
settings = list(
  name = "TD",
  mode = "simulating",
  estimate = "MLE",
  policy = "on"
)

model = multiRL::TD
priors = list(
  alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
  beta = function(x) {stats::rexp(n = 1, rate = 1)}
)
control = list(sample = 100)
```


```{r}
multiRL.env <- multiRL::estimate_0_ENV(
  data = data,
  behrule = behrule,
  colnames = colnames,
  settings = settings,
)

list_simulated <- multiRL::estimate_2_SBI(
  model = multiRL::TD,
  env = multiRL.env,
  priors = priors,
  control = control
)
```

```{r}
.list2df <- function(list, subid) {
  
  list_data <- list()
  list_params <- list()
  
  for (i in 1:length(list)) {
    list_data[[i]] <- list[[i]]$data
    list_data[[i]][[subid]] <- i
    
    list_params[[i]] <- as.data.frame(list[[i]]$params)
    list_params[[i]][[subid]] <- i
  }
  
  df_data <- do.call(rbind, list_data)
  df_params <- do.call(rbind, list_params)
  
  dfs <- list(
    data = df_data, 
    params = df_params
  )
  
  return(dfs)
}
```


```{r}
df_simulated <- .list2df(list = list_simulated, subid = "Subject")
```

```{r}
test_MLE <- estimation_methods(
  estimate = "MLE",
  data = df_simulated$data,
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD, multiRL::RSTD, multiRL::Utility),
  settings = list(
    list(name = "TD", policy = "off"), 
    list(name = "RSTD", policy = "off"), 
    list(name = "Utility", policy = "off")
  ),
  algorithm = c("NLOPT_GN_MLSL", "NLOPT_LN_BOBYQA"),
  lowers = list(c(0, 0), c(0, 0, 0), c(0, 0, 0)),
  uppers = list(c(1, 5), c(1, 1, 5), c(1, 1, 5)),
  control = list(core = 10, iter = 100)
)
```

```{r}
cor(df_simulated$params$alpha, test_MLE[test_MLE[, "fit_model"] == "TD", ]$alpha)

cor(df_simulated$params$beta, test_MLE[test_MLE[, "fit_model"] == "TD", ]$beta)
```

## MLE

```{r}
test <- rcv_d(
  estimate = "MLE",
  data = multiRL::TAB %>% dplyr::filter(Subject %in% 1:10),
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD, multiRL::RSTD, multiRL::Utility),
  settings = list(list(name = "TD"), list(name = "RSTD"), list(name = "Utility")),
  priors = list(
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    ),
    list(
      alphaN = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      alphaP = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    ),
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)},
      gamma = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}
    )
  ),
  
  algorithm = c("NLOPT_GN_MLSL", "NLOPT_LN_BOBYQA"),
  lowers = list(c(0, 0), c(0, 0, 0), c(0, 0, 0)),
  uppers = list(c(1, 1), c(1, 1, 1), c(1, 1, 1)),
  control = list(core = 1, sample = 10, iter = 10)
)
```

## MAP

```{r}
test <- rcv_d(
  estimate = "MAP",
  data = multiRL::TAB %>% dplyr::filter(Subject %in% 1:10),
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD, multiRL::RSTD, multiRL::Utility),
  priors = list(
    TD = list(
      alpha = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    ),
    RSTD = list(
      alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    ),
    Utility = list(
      alpha = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)},
      gamma = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}
    )
  ),
  settings = list(list(name = "TD"), list(name = "RSTD"), list(name = "Utility")),
  
  algorithm = c("NLOPT_GN_MLSL", "NLOPT_LN_BOBYQA"),
  lowers = list(c(0, 0), c(0, 0, 0), c(0, 0, 0)),
  uppers = list(c(1, 5), c(1, 1, 5), c(1, 5, 1)),
  control = list(sample = 10, core = 10, iter = c(10, 3))
)
```

## RNN

```{r}
reticulate::use_condaenv(condaenv = "tf-gpu", required = TRUE)
```

```{r}
test <- rcv_d(
  estimate = "RNN",
  data = multiRL::TAB %>% dplyr::filter(Subject %in% 1:3),
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD, multiRL::RSTD, multiRL::Utility),
  
  priors = list(
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    ),
    list(
      alphaN = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      alphaP = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)}
    ),
    list(
      alpha = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}, 
      beta = function(x) {stats::rexp(n = 1, rate = 1)},
      gamma = function(x) {stats::rbeta(n = 1, shape1 = 2, shape2 = 2)}
    )
  ),
  settings = list(list(name = "TD"), list(name = "RSTD"), list(name = "Utility")),
  
  control = list(
    layer = "GRU",
    units = 128,
    sample = 100,
    batch_size = 10,
    epochs = 10
  )
)
```

```{r}
true <- test$simulate$TD$alpha

pred <- test$recovery$TD %>%
  dplyr::filter(fit_model == "TD")

pred <- pred$alpha

cor(true, pred)
```

