---
title: "Untitled"
author: "yuki"
date: "2025-12-03"
output: html_document
---
## MLE

```{r}
recovery.MLE <- multiRL::rcv_d(
  estimate = "MLE",
  data = multiRL::TAB,
  id = 1,
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD),
  priors = list(
    TD = list(
      alpha = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    )
  ),
  settings = list(list(name = "TD")),
  
  algorithm = "DEoptim",
  lowers = list(c(0, 0)),
  uppers = list(c(1, 5)),
  control = list(sample = 100, core = 10, iter = 100)
)
```

```{r}
# alpha
df_true <- recovery.MLE$simulate$TD$alpha
df_pred <- recovery.MLE$recovery$TD %>%
  dplyr::filter(fit_model == "TD")
df_pred <- df_pred$alpha

cor(df_true, df_pred)

# alpha
df_true <- recovery.MLE$simulate$TD$beta
df_pred <- recovery.MLE$recovery$TD %>%
  dplyr::filter(fit_model == "TD")
df_pred <- df_pred$beta

cor(df_true, df_pred)
```


```{r}
recovery.MAP <- multiRL::rcv_d(
  estimate = "MAP",
  data = multiRL::TAB %>% dplyr::filter(Subject %in% 1:10),
  id = 1,
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD, multiRL::RSTD, multiRL::Utility),
  priors = list(
    TD = list(
      alpha = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    ),
  ),
  settings = list(list(name = "TD")),
  
  algorithm = c("NLOPT_GN_MLSL", "NLOPT_LN_BOBYQA"),
  lowers = list(c(0, 0), c(0, 0, 0), c(0, 0, 0)),
  uppers = list(c(1, 5), c(1, 1, 5), c(1, 1, 5)),
  control = list(sample = 100, core = 10, iter = c(100, 100))
)
```

# RNN (pass)

```{r}
reticulate::use_condaenv(condaenv = "tf-gpu", required = TRUE)
```

```{r}
recovery.RNN <- multiRL::rcv_d(
  estimate = "RNN",
  data = multiRL::TAB %>% dplyr::filter(Subject %in% 1:10),
  id = 1,
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  
  colnames = list(
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  models = list(multiRL::TD),
  priors = list(
    TD = list(
      alpha = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    )
  ),
  settings = list(list(name = "TD")),
  control = list(
    layer = "GRU",
    sample = 100,
    train = 1000,
    units = 128,
    batch_size = 10,
    epochs = 100
  )
)
```

```{r}
# alpha
df_true <- recovery.RNN$simulate$TD$alpha
df_pred <- recovery.RNN$recovery$TD %>%
  dplyr::filter(fit_model == "TD")
df_pred <- df_pred$alpha

cor(df_true, df_pred)

# alpha
df_true <- recovery.RNN$simulate$TD$beta
df_pred <- recovery.RNN$recovery$TD %>%
  dplyr::filter(fit_model == "TD")
df_pred <- df_pred$beta

cor(df_true, df_pred)
```