---
title: "Untitled"
author: "yuki"
date: "2025-10-15"
output: html_document
---
# multiRL

```{r}
multiRL.input <- process_1_input(
  data = multiRL::MAB[multiRL::MAB[, "Subject"] == 1, ],
  colnames = list(
    subid = "Subject", block = "Block", trial = "Trial",
    object = NA_character_, reward = NA_character_, action = "Action"
  ),
  params = list(
    free = list(
      alphaN = 0.3,
      alphaP = 0.7,
      beta = 0.5
    ),
    fixed = list(
      gamma = 1,
      delta = 0.1,
      epsilon = 0.1,
      zeta = 1,
      eta = NA_real_
    ),
    constant = list(
      Q1 = NA_real_,
      lapse = 0.01
    )
  ),
  priors = list(
    alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
  ),
  funcs = list(
    rate_func = multiRL::func_alpha,
    prob_func = multiRL::func_beta,
    util_func = multiRL::func_gamma,
    bias_func = multiRL::func_delta,
    expl_func = multiRL::func_epsilon
  ),
  settings = list(
    name = "RSTD",
    mode = "fitting",
    estimate = "ABC",
    policy = "on"
  )
)
```

```{r}
multiRL.behrule <- process_2_behrule(
  behrule = list(
    cue = c("Red", "Yellow", "Green", "Blue"),
    rsp = c("Up", "Down", "Left", "Right")
  )
)
```

```{r}
multiRL.record <- process_3_record(
  input = multiRL.input,
  behrule = multiRL.behrule
)
```

```{r}
multiRL.output <- process_4_output(
  record = multiRL.record
)
```

```{r}
multiRL.metric <- process_5_metric(
  output = multiRL.output
)
```

```{r}
View(multiRL.output@result@value)
View(multiRL.output@result@reward)
View(multiRL.output@result@utility)
View(multiRL.output@result@count)
View(multiRL.output@result@bias)
View(multiRL.output@result@shown)
View(multiRL.output@result@exploration)
View(multiRL.output@result@prob)
```

```{r}
multiRL.model <- run_m(
  data = multiRL::MAB[multiRL::MAB[, "Subject"] == 1, ],
  behrule = list(
    cue = c("Red", "Yellow", "Green", "Blue"),
    rsp = c("Up", "Down", "Left", "Right")
  ),
  params = list(
    free = list(
      alphaN = 0.3,
      alphaP = 0.7,
      beta = 0.5
    ),
    fixed = list(
      gamma = 1,
      delta = 0.1,
      epsilon = 0.1,
      zeta = 1,
      eta = NA_real_
    ),
    constant = list(
      Q1 = NA_real_,
      lapse = 0.01
    )
  ),
  settings = list(
    name = "unknown",
    mode = "fitting",
    estimate = "MLE",
    policy = "on"
  ),
  whatyousay = c(1, 2, 3)
)

multiRL.summary <- multiRL::summary(multiRL.model)
```

```{r}
obj_func_r <- function(x){
  multiRL.model <- run_m(
    data = multiRL::MAB[multiRL::MAB[, "Subject"] == 1, ],
    behrule = list(
      cue = c("Red", "Yellow", "Green", "Blue"),
      rsp = c("Up", "Down", "Left", "Right")
    ),
    params = list(
      free = list(
        alphaN = 0.3,
        alphaP = 0.7,
        beta = 0.5
      ),
      fixed = list(
        gamma = 1,
        delta = 0.1,
        epsilon = 0.1,
        zeta = 1,
        eta = NA_real_
      ),
      constant = list(
        Q1 = NA_real_,
        lapse = 0.01
      )
    ),
    settings = list(
      name = "unknown",
      mode = "fitting",
      estimate = "MLE",
      policy = "on"
    ),
    whatyousay = c(1, 2, 3)
  )
}

microbenchmark::microbenchmark(
  "r" = { obj_func_r() },
  #"cpp" = { obj_func_cpp() },
  times = 50
)
```

## binaryRL

```{r}
binaryRL.res <- binaryRL::run_m(
  mode = "fit",
  data = binaryRL::Mason_2024_G2,
  id = 1,
  n_params = 3,
  n_trials = 360,
  initial_value = 100,
  threshold = 1,
  pi = 0.1,
  epsilon = NA_real_,
  eta = c(0.123, 0.456),
  tau = c(0.789), 
  priors = list(
    eta = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    tau = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
  ),
  policy = "off"
)

summary(binaryRL.res)
```

```{r}
multiRL.input <- process_1_input(
  data = multiRL::TAB[multiRL::TAB[, "Subject"] == 1, ],
  colnames = list(
    subid = "Subject", 
    block = "Block",
    trial = "Trial",
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose",
    exinfo = c("Frame", "NetWorth", "RT")
    #extra = NA_character_
  ),
  params = list(
    free = list(
      alphaN = 0.3,
      alphaP = 0.7,
      beta = 0.789
    ),
    fixed = list(
      gamma = 1,
      delta = 0.1,
      epsilon = NA_real_,
      zeta = 1,
      eta = NA_real_
    ),
    constant = list(
      Q1 = NA_real_,
      lapse = 0.01
    )
  ),
  priors = list(
    alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)},
    alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)},
    beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
  ),
  funcs = list(
    rate_func = multiRL::func_alpha,
    prob_func = multiRL::func_beta,
    util_func = multiRL::func_gamma,
    bias_func = multiRL::func_delta,
    expl_func = multiRL::func_epsilon
  ),
  settings = list(
    name = "RSTD",
    mode = "fitting",
    estimate = "MLE",
    policy = "on"
  )
)
```

```{r}
multiRL.behrule <- process_2_behrule(
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  )
)
```

```{r}
multiRL.record <- process_3_record(
  input = multiRL.input,
  behrule = multiRL.behrule
)
```

```{r}
multiRL.output <- process_4_output(
  record = multiRL.record
)
```

```{r}
multiRL.metric <- process_5_metric(
  output = multiRL.output
)
```

```{r}
View(multiRL.output@input@features@action)
View(multiRL.output@result@value)
View(multiRL.output@result@reward)
View(multiRL.output@result@utility)
View(multiRL.output@result@count)
View(multiRL.output@result@bias)
View(multiRL.output@result@shown)
View(multiRL.output@result@prob)
View(multiRL.output@result@simulation)
View(multiRL.output@result@latent)
```

```{r}
multiRL.model <- multiRL::run_m(
  data = multiRL::TAB[multiRL::TAB[, "Subject"] == 1, ],
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  colnames = list(
    subid = "Subject", block = "Block", trial = "Trial",
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose",
    exinfo = c("Frame", "NetWorth", "RT")
  ),
  params = list(
    free = list(
      alphaN = 0.3,
      alphaP = 0.7,
      beta = 0.789
    ),
    fixed = list(
      gamma = 1,
      delta = 0.1,
      epsilon = NA_real_,
      zeta = 1,
      eta = NA_real_
    ),
    constant = list(
      Q1 = NA_real_,
      lapse = 0.01
    )
  ),
  priors = list(
    alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
    beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
  ),
  settings = list(
    name = "RSTD",
    mode = "fitting",
    estimate = "MLE",
    policy = "on"
  ),
  anythingelse = c(1, 2, 3)
)

multiRL.summary <- multiRL::summary(multiRL.model)
```


# CPP
---
title: "Untitled"
author: "yuki"
date: "2025-11-17"
output: html_document
---

```{r}
library(Rcpp)
```

```{r}
Rcpp::sourceCpp("../../src/tool_get_param.cpp")
test_params <- multiRL.model@input@params

alpha <- get_param(x = test_params, name = "alpha")
```


```{r}
Rcpp::sourceCpp("../../src/tool_record_shown.cpp")
test_state <- multiRL.model@input@features@state[13, , ]
test_cue <- multiRL.model@behrule@cue

test_state
test_cue

record_shown(state = test_state, cue = test_cue)
```

```{r}
Rcpp::sourceCpp("../../src/tool_sample_choice.cpp")
test_prob <- multiRL.model@result@prob[1, ]
test_shown <- multiRL.model@result@shown[1, ]
test_cue <- multiRL.model@behrule@cue

test_state
test_cue

sample_choice(test_prob, test_shown, test_cue)
```

```{r}
Rcpp::sourceCpp("../../src/process_4_output.cpp")
```

```{r}

multiRL.record <- process_3_record(
  input = multiRL.input,
  behrule = multiRL.behrule
)

multiRL.output <- process_4_output_cpp(
  record = multiRL.record
)
```

```{r}
microbenchmark::microbenchmark(
  "R" = multiRL.output <- process_4_output_r(
    record = multiRL.record
  ),
  "C" = multiRL.output <- process_4_output_cpp(
    record = multiRL.record
  ),
  times = 50L,  
  unit = "ms"   
)
```


```{r}
obj_func_r <- function(x) {
  multiRL.model <- multiRL::run_m(
    data = multiRL::TAB[multiRL::TAB[, "Subject"] == 1, ],
    behrule = list(
      cue = c("A", "B", "C", "D"),
      rsp = c("A", "B", "C", "D")
    ),
    colnames = list(
      subid = "Subject", block = "Block", trial = "Trial",
      object = c("L_choice", "R_choice"), 
      reward = c("L_reward", "R_reward"),
      action = "Sub_Choose",
      exinfo = c("Frame", "NetWorth", "RT")
    ),
    params = list(
      free = list(
        alphaN = 0.3,
        alphaP = 0.7,
        beta = 0.789
      ),
      fixed = list(
        gamma = 1,
        delta = 0.1,
        epsilon = NA_real_,
        zeta = 1,
        eta = NA_real_
      ),
      constant = list(
        Q1 = NA_real_,
        lapse = 0.01
      )
    ),
    priors = list(
      alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    ),
    settings = list(
      name = "RSTD",
      mode = "fitting",
      estimate = "MLE",
      policy = "on"
    ),
    engine = "R"
  )
}

obj_func_c <- function(x) {
  multiRL.model <- multiRL::run_m(
    data = multiRL::TAB[multiRL::TAB[, "Subject"] == 1, ],
    behrule = list(
      cue = c("A", "B", "C", "D"),
      rsp = c("A", "B", "C", "D")
    ),
    colnames = list(
      subid = "Subject", block = "Block", trial = "Trial",
      object = c("L_choice", "R_choice"), 
      reward = c("L_reward", "R_reward"),
      action = "Sub_Choose",
      exinfo = c("Frame", "NetWorth", "RT")
    ),
    params = list(
      free = list(
        alphaN = 0.3,
        alphaP = 0.7,
        beta = 0.789
      ),
      fixed = list(
        gamma = 1,
        delta = 0.1,
        epsilon = NA_real_,
        zeta = 1,
        eta = NA_real_
      ),
      constant = list(
        Q1 = NA_real_,
        lapse = 0.01
      )
    ),
    priors = list(
      alphaN = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      alphaP = function(x) {stats::dbeta(x, shape1 = 2, shape2 = 2, log = TRUE)}, 
      beta = function(x) {stats::dexp(x, rate = 1, log = TRUE)}
    ),
    settings = list(
      name = "RSTD",
      mode = "fitting",
      estimate = "MLE",
      policy = "on"
    ),
    engine = "Cpp"
  )
}
```

```{r}
profvis::profvis({
  obj_func_r()
})
```

```{r}
original_obj_func <- obj_func_r
compiled_obj_func <- compiler::cmpfun(obj_func_r)

microbenchmark::microbenchmark(
  "original" = { original_obj_func() },
  "compiled" = { compiled_obj_func() },
  times = 50
)
```
```{r}
original_obj_func <- obj_func_c
compiled_obj_func <- compiler::cmpfun(obj_func_c)

microbenchmark::microbenchmark(
  "original" = { original_obj_func() },
  "compiled" = { compiled_obj_func() },
  times = 50
)
```


```{r}
microbenchmark::microbenchmark(
  "R" = obj_func_r(),
  "C" = obj_func_c(),
  times = 50L,  
  unit = "ms"   
)
```

```{r}
microbenchmark::microbenchmark(
  "R_Original" = process_4_output(
    record = multiRL.record
  ),
  "Cpp_Rcpp" = process_4_output_cpp(
    record = multiRL.record
  ),
  times = 50L,  
  unit = "ms"   
)
```