// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// process_4_output_cpp
Rcpp::S4 process_4_output_cpp(const Rcpp::S4 record, const Rcpp::List& extra);
RcppExport SEXP _multiRL_process_4_output_cpp(SEXP recordSEXP, SEXP extraSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::S4 >::type record(recordSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type extra(extraSEXP);
    rcpp_result_gen = Rcpp::wrap(process_4_output_cpp(record, extra));
    return rcpp_result_gen;
END_RCPP
}
// record_shown
Rcpp::NumericVector record_shown(const Rcpp::CharacterMatrix& state, const Rcpp::CharacterVector& cue);
RcppExport SEXP _multiRL_record_shown(SEXP stateSEXP, SEXP cueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterMatrix& >::type state(stateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type cue(cueSEXP);
    rcpp_result_gen = Rcpp::wrap(record_shown(state, cue));
    return rcpp_result_gen;
END_RCPP
}
// sample_choice
std::string sample_choice(const Rcpp::NumericVector& prob_row, const Rcpp::NumericVector& shown_row, const Rcpp::CharacterVector& cues);
RcppExport SEXP _multiRL_sample_choice(SEXP prob_rowSEXP, SEXP shown_rowSEXP, SEXP cuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type prob_row(prob_rowSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type shown_row(shown_rowSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type cues(cuesSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_choice(prob_row, shown_row, cues));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiRL_process_4_output_cpp", (DL_FUNC) &_multiRL_process_4_output_cpp, 2},
    {"_multiRL_record_shown", (DL_FUNC) &_multiRL_record_shown, 2},
    {"_multiRL_sample_choice", (DL_FUNC) &_multiRL_sample_choice, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiRL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
