#' @title Cognitive Processing System
#' @name system
#' @description 
#' 
#'   Value updating is governed by the strategic interaction of two distinct 
#'   computational systems. While both systems aim to minimize 
#'   prediction errors, they operate on different timescales and under 
#'   different biological constraints. The final decision policy is 
#'   a weighted mixture of the action-values generated by these two systems, 
#'   representing a trade-off between the stability of long-term habits and 
#'   the flexibility of immediate memory.
#'    
#' @section Class: 
#' \code{system [Character]} 
#' 
#' @section Detail:
#'   \itemize{
#'     \item Reinforcement Learning: An incremental, model-free system that 
#'           integrates reward history over long timescales to build stable 
#'           action-value representations through prediction errors. 
#'           It is robust but slow to adapt to sudden changes.
#'           
#'     \item Working Memory: A rapid-acquisition system that allows for 
#'           near-instantaneous updating of stimulus-response associations. 
#'           However, its contribution is strictly constrained by 
#'           limited storage capacity and is highly susceptible to decay 
#'           over time or interference from intervening trials.
#'  }
#'
#' @section Example:
#' \itemize{
#'    \item \code{system = "RL"}: 
#'          A single-system model based on incremental Reinforcement Learning 
#'          (RL). The agent updates option values using a learning 
#'          rate (alpha) typically less than 1, representing a slow, 
#'          integrative process linked to corticostriatal circuitry.
#'         
#'    \item \code{system = "WM"}: 
#'          A single-system model representing Working Memory (WM). 
#'          Unlike RL, this system has the capacity to instantly update values 
#'          with a fixed learning rate of 1, effectively "remembering" the 
#'          most recent outcome for each stimulus.
#'         
#'    \item \code{system = c("RL", "WM")}: 
#'          A hybrid model where RL and WM systems operate in parallel, 
#'          maintaining two distinct Q-value tables. The final 
#'          decision is a weighted integration of both systems' choice 
#'          probabilities. The contribution of WM is constrained 
#'          by its \code{capacity}; if the stimulus set size exceeds 
#'          \code{capacity}, the agent's reliance shifts toward the RL 
#'          system as the WM reliability diminishes.
#'  }
#'
#' @references 
#' Collins, A. G., & Frank, M. J. (2012). How much of reinforcement learning 
#' is working memory, not reinforcement learning? A behavioral, computational, 
#' and neurogenetic analysis. \emph{European Journal of Neuroscience, 35}(7), 
#' 1024-1035.
#' \doi{10.1111/j.1460-9568.2011.07980.x}
#' 
NULL