# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' multiRL.output
#'
#' @param multiRL.record
#' @param A list of extra information passed from R.
#' @export
process_4_output_cpp <- function(record, extra) {
    .Call(`_multiRL_process_4_output_cpp`, record, extra)
}

get_param <- function(x, name) {
    .Call(`_multiRL_get_param`, x, name)
}

record_shown <- function(state, cue) {
    .Call(`_multiRL_record_shown`, state, cue)
}

sample_choice <- function(prob_row, shown_row, cues) {
    .Call(`_multiRL_sample_choice`, prob_row, shown_row, cues)
}

