---
title: "Untitled"
author: "yuki"
date: "2025-10-15"
output: html_document
---
```{r}
initial_value = 2

feature <- multiRL.record@input@features@state

cue <- multiRL.record@behrules@cue
rsp <- multiRL.record@behrules@rsp

value <- multiRL.record@output@value
bias <- multiRL.record@output@bias
utility <- multiRL.record@output@utility
shown <- multiRL.record@output@shown
prob <- multiRL.record@output@prob

latent <- multiRL.record@output@latent
reward <- multiRL.record@output@reward
simulation <- multiRL.record@output@simulation
```

```{r}
set.seed(123)
# 初始值
value[1, ] <- initial_value
# 偏差值func_pi
bias[1, ] <- 0
# 选项是否出现
shown[1, ] <- stats::setNames(
  object = as.numeric(cue %in% feature[1, , ]),
  nm = cue
)
# 主观价值func_gamma
utility[1, ] <- func_gamma(x = value[1, ], gamma = 2)
utility[1, ] <- utility[1, ] * shown[1, ]
# 价值转概率func_beta
prob[1, ] <- func_beta(x = utility[1, ], beta = 1)
# 根据概率, 进行选择内在选择
latent[1, ] <- sample(
  x = colnames(prob),
  size = 1, prob = prob[1, ]
)
# 内在选择所在行
row_index <- which(feature[1, , ] == latent[1, ])
# 外在选择所在列
col_index <- which(feature[1, row_index, ] %in% rsp)
# 根据内在选择[行, 列], 定位外在选择
simulation[1, ] <- feature[1, row_index, col_index]
# 根据内在选择定位奖励
reward[1, ] <- feature[1, row_index, dim(feature)[3]]
```

```{r}
value[2, ] <- value[1, ]
value[2, latent[1, ]] <- func_alpha(
  qvalue = as.numeric(value[1, latent[1, ]]),
  reward = as.numeric(reward[1, ]), 
  alpha = 0.5
)
```

```{r}
set.seed(123)

for (i in 1:(multiRL.record@input@n_rows - 1)) {
  
  # 只有第一次需要获取初始值
  if (i == 1) {value[i, ] <- initial_value} 
  
  # 偏差值func_pi
  bias[i, ] <- 0
  # 选项是否出现
  shown[i, ] <- stats::setNames(
    object = as.numeric(cue %in% feature[i, , ]),
    nm = cue
  )
  # 主观价值func_gamma
  utility[i, ] <- func_gamma(x = value[i, ], gamma = 2)
  utility[i, ] <- utility[i, ] * shown[i, ]
  # 价值转概率func_beta
  prob[i, ] <- func_beta(x = utility[i, ], beta = 1)
  # 根据概率, 进行选择内在选择
  latent[i, ] <- sample(x = colnames(prob), prob = prob[i, ], size = 1)
  # 内在选择所在行
  row_index <- which(feature[i, , ] == latent[i, ])
  # 外在选择所在列
  col_index <- which(feature[i, row_index, ] %in% rsp)
  # 根据内在选择[行, 列], 定位外在选择
  simulation[i, ] <- feature[i, row_index, col_index]
  # 根据内在选择定位奖励
  reward[i, ] <- feature[i, row_index, dim(feature)[3]]
  # 传递到下一行
  value[i + 1, ] <- value[i, ]
  # 基于PE价值更新
  value[i + 1, latent[i, ]] <- func_alpha(
    qvalue = as.numeric(value[i, latent[i, ]]),
    reward = as.numeric(reward[i, ]), 
    alpha = 0.5
  )
}
```

