---
title: "Untitled"
author: "yuki"
date: "2025-10-15"
output: html_document
---
# multiRL

```{r}
multiRL.input <- process_1_input(
  data = read.csv("../DATA/DATA.csv") |> dplyr::filter(Subject == 1),
  colnames = list(
    subid = "Subject", 
    block = "Block",
    trial = "Trial",
    
    object = c("Object_1", "Object_2", "Object_3", "Object_4"), 
    reward = c("Reward_1", "Reward_2", "Reward_3", "Reward_4"),
    action = "Action"
  ),
  params = list(
    fixed = list(
      Q1 = 0,
      gamma = 1,
      delta = 0.1,
      epsilon = 0.1,
      zeta = 1,
      eta = NA_real_
    ),
    free = list(
      alpha = c(0.3, 0.7),
      beta = 0.5
    )
  ),
  funcs = list(
    rate_func = func_alpha,
    prob_func = func_beta,
    util_func = func_gamma,
    bias_func = func_delta,
    expl_func = func_epsilon
  )
)
```

```{r}
multiRL.behrule <- process_2_behrule(
  behrule = list(
    cue = c("Red", "Yellow", "Green", "Blue"),
    rsp = c("Up", "Down", "Left", "Right")
  )
)
```

```{r}
multiRL.record <- process_3_record(
  input = multiRL.input,
  behrule = multiRL.behrule
)
```

```{r}
multiRL.output <- process_4_output(
  record = multiRL.record
)
```

```{r}
multiRL.metric <- process_5_metric(
  output = multiRL.output
)
```

```{r}
View(multiRL.output@result@value)
View(multiRL.output@result@reward)
View(multiRL.output@result@utility)
View(multiRL.output@result@count)
View(multiRL.output@result@bias)
View(multiRL.output@result@shown)
View(multiRL.output@result@exploration)
View(multiRL.output@result@prob)
```

```{r}
obj_func <- function(x){
  multiRL.input <- process_1_input(
    data = read.csv("../DATA/DATA.csv") |> dplyr::filter(Subject == 1),
    colnames = list(
      subid = "Subject", 
      block = "Block",
      trial = "Trial",
      
      object = c("Object_1", "Object_2", "Object_3", "Object_4"), 
      reward = c("Reward_1", "Reward_2", "Reward_3", "Reward_4"),
      action = "Action"
    ),
    params = list(
      fixed = list(
        Q1 = 0,
        gamma = 1,
        delta = 0.1,
        epsilon = 0.1,
        zeta = 1,
        eta = NA_real_
      ),
      free = list(
        alpha = c(0.3, 0.7),
        beta = 0.5
      )
    ),
    funcs = list(
      rate_func = func_alpha,
      prob_func = func_beta,
      util_func = func_gamma,
      bias_func = func_delta,
      expl_func = func_epsilon
    )
  )
  
  multiRL.behrule <- process_2_behrule(
    behrule = list(
      cue = c("Red", "Yellow", "Green", "Blue"),
      rsp = c("Up", "Down", "Left", "Right")
    )
  )
  
  multiRL.record <- process_3_record(
    input = multiRL.input,
    behrule = multiRL.behrule
  )
  
  multiRL.output <- process_4_output(record = multiRL.record)
  
  multiRL.metric <- process_5_metric(output = multiRL.output)
  
  return(multiRL.metric)
}
```

```{r}
multiRL.model <- run_m(
  data = read.csv("../DATA/DATA.csv") |> dplyr::filter(Subject == 1),
  colnames = list(
    subid = "Subject", 
    block = "Block",
    trial = "Trial",
    
    object = c("Object_1", "Object_2", "Object_3", "Object_4"), 
    reward = c("Reward_1", "Reward_2", "Reward_3", "Reward_4"),
    action = "Action"
  ),
  params = list(
    fixed = list(
      Q1 = 0,
      gamma = 1,
      delta = 0.1,
      epsilon = 0.1,
      zeta = 1,
      eta = NA_real_
    ),
    free = list(
      alpha = c(0.3, 0.7),
      beta = 0.5
    )
  ),
  funcs = list(
    rate_func = func_alpha,
    prob_func = func_beta,
    util_func = func_gamma,
    bias_func = func_delta,
    expl_func = func_epsilon
  ),
  behrule = list(
    cue = c("Red", "Yellow", "Green", "Blue"),
    rsp = c("Up", "Down", "Left", "Right")
  ),
  whatyousay = c(1, 2, 3)
)
```


```{r}
profvis::profvis({
  test <- obj_func()
})
```

```{r}
test <- obj_func()
```

```{r}
microbenchmark::microbenchmark(
  "r" = { obj_func() },
  times = 100
)
```


## binaryRL

```{r}
binaryRL.res <- binaryRL::run_m(
  mode = "replay",
  data = binaryRL::Mason_2024_G2,
  id = 1,
  n_params = 3,
  n_trials = 360,
  initial_value = 100,
  threshold = 1,
  pi = 0.1,
  epsilon = NA_real_,
  eta = c(0.123, 0.456),
  tau = c(0.789), 
  priors = NULL
)

summary(binaryRL.res)
```


```{r}
multiRL.input <- process_1_input(
  data = binaryRL::Mason_2024_G2 |> dplyr::filter(Subject == 1),
  colnames = list(
    subid = "Subject", 
    block = "Block",
    trial = "Trial",
    
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  params = list(
    fixed = list(
      Q1 = 100,
      gamma = 1,
      delta = 0.1,
      epsilon = NA_real_,
      zeta = 1,
      eta = NA_real_
    ),
    free = list(
      alpha = c(0.123, 0.456),
      beta = 0.789
    )
  ),
  funcs = list(
    rate_func = func_alpha,
    prob_func = func_beta,
    util_func = func_gamma,
    bias_func = func_delta,
    expl_func = func_epsilon
  )
)
```

```{r}
multiRL.behrule <- process_2_behrule(
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  )
)
```

```{r}
multiRL.record <- process_3_record(
  input = multiRL.input,
  behrule = multiRL.behrule
)
```

```{r}
multiRL.output <- process_4_output(
  record = multiRL.record
)
```

```{r}
multiRL.metric <- process_5_metric(
  output = multiRL.output
)
```

```{r}
View(multiRL.output@result@value)
View(multiRL.output@result@reward)
View(multiRL.output@result@utility)
View(multiRL.output@result@count)
View(multiRL.output@result@bias)
View(multiRL.output@result@shown)
View(multiRL.output@result@prob)
```

```{r}
multiRL.model <- run_m(
  data = binaryRL::Mason_2024_G2 |> dplyr::filter(Subject == 1),
  colnames = list(
    subid = "Subject", 
    block = "Block",
    trial = "Trial",
    
    object = c("L_choice", "R_choice"), 
    reward = c("L_reward", "R_reward"),
    action = "Sub_Choose"
  ),
  params = list(
    fixed = list(
      Q1 = 100,
      gamma = 1,
      delta = 0.1,
      epsilon = NA_real_,
      zeta = 1,
      eta = NA_real_
    ),
    free = list(
      alpha = c(0.123, 0.456),
      beta = 0.789
    )
  ),
  funcs = list(
    rate_func = func_alpha,
    prob_func = func_beta,
    util_func = func_gamma,
    bias_func = func_delta,
    expl_func = func_epsilon
  ),
  behrule = list(
    cue = c("A", "B", "C", "D"),
    rsp = c("A", "B", "C", "D")
  ),
  whatyousay = c(1, 2, 3)
)
```

```{r}
test <- summary(multiRL.model)
```

